#

rm -rf obj bin
rm -rf */obj */bin
rm -rf */*/obj */*/bin

for i in `grep -l -R 'This code was generated by a tool' .`
do
	if [ "$i" != "./clean.sh" ]
	then
		echo $i
		rm $i
	fi
done

for i in `find . -name '*.tokens'`
do
	if [ "$i" != "./mysql/predefined.tokens" ]
	then
		echo $i
		rm $i
	fi
done

for i in `find . -name '*.interp'`
do
	echo $i
	rm $i
done
